// external packages
export 'package:cloud_firestore/cloud_firestore.dart';
export 'package:connectivity_plus/connectivity_plus.dart';
export 'package:easy_localization/easy_localization.dart' hide TextDirection;
export 'package:equatable/equatable.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:firebase_storage/firebase_storage.dart';
export 'package:flutter/cupertino.dart';
export 'package:flutter/foundation.dart';
export 'package:flutter/material.dart' hide RefreshCallback;
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:flutter_local_notifications/flutter_local_notifications.dart';
export 'package:flutter_native_splash/flutter_native_splash.dart';
export 'package:flutter_painter_v2/flutter_painter.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:flutter_staggered_animations/flutter_staggered_animations.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:get_it/get_it.dart';
export 'package:go_router/go_router.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:image_picker/image_picker.dart';
export 'package:intl/intl.dart' hide TextDirection;
export 'package:logger/logger.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'dart:async';
// internal packages
export 'package:simple_paint/app/app_barrels.dart';
export 'package:simple_paint/core/constants/constants.dart';
export 'package:simple_paint/core/di/di.dart';
export 'package:simple_paint/core/errors/errors.dart';
export 'package:simple_paint/core/errors/exceptions.dart';
export 'package:simple_paint/core/localization/localization.dart';
export 'package:simple_paint/core/network/network.dart';
export 'package:simple_paint/core/observer/observer.dart';
export 'package:simple_paint/core/router/router.dart';
export 'package:simple_paint/core/services/services.dart';
export 'package:simple_paint/core/styles/styles.dart';
export 'package:simple_paint/core/widgets/widgets.dart';
